=== chyrtsik/warehouse-redo/warehouse-redo/modules/core/src/main/resources/xsd/resources_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2007-2011 Artigile.
  ~ Software art development company.
  ~ All Rights Reserved.
  ~
  ~ This software is the confidential and proprietary information of Artigile. ("Confidential Information").
  ~ You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the
  ~ license agreement you entered into with Artigile software company.
  -->

<!-- resources.xml schema -->
<xsd:schema targetNamespace="http://artigile.by/xml/ns/resources"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:resources="http://artigile.by/xml/ns/resources"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  version="1.0">

    <xsd:annotation>
      <xsd:documentation>
        @(#)resources_1_0.xsd  1.0  April 26 2010
      </xsd:documentation>
    </xsd:annotation>

    <xsd:annotation>
      <xsd:documentation>

        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

        Copyright (c) 2007-2011 Artigile.
        Software art development company.
        All Rights Reserved.

        This software is the confidential and proprietary information of Artigile. ("Confidential Information").
        You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the
        license agreement you entered into with Artigile software company.

      </xsd:documentation>
    </xsd:annotation>

    <xsd:annotation>
       <xsd:documentation><![CDATA[

       This is the XML Schema for the resources configuration file.
       The file must be named "config/resources.xml" in the 
       application folder.
       Resources configuration files must indicate
       the resources schema by using the resources namespace:

       http://java.sun.com/xml/ns/resources

       and indicate the version of the schema by
       using the version element as shown below:

        <resources xmlns="http://artigile.by/xml/ns/resources"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://artigile.by/xml/ns/resources
            http://artigile.by/xml/ns/resources/resources_1_0.xsd"
          version="1.0">
            ...
        </resources>

      ]]></xsd:documentation>
    </xsd:annotation>

    <xsd:simpleType name="versionType">
      <xsd:restriction base="xsd:token">
        <xsd:pattern value="[0-9]+(\.[0-9]+)*"/>
      </xsd:restriction>
    </xsd:simpleType>

    <!-- **************************************************** -->

    <xsd:element name="resources">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element type="resources:server" name="server"/>
            <xsd:element type="resources:datasource" name="datasource"/>
            <xsd:element type="resources:jdbc-resource-pool" name="jdbc-resource-pool"/>
        </xsd:choice>

        <xsd:attribute name="version" type="resources:versionType"
                       fixed="1.0" use="required"/>
      </xsd:complexType>
    </xsd:element>

    <!-- **************************************************** -->

    <xsd:complexType name="server">
      <xsd:annotation>
        <xsd:documentation>
            TODO:
        </xsd:documentation>
      </xsd:annotation>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="datasource-name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- **************************************************** -->

    <xsd:complexType name="datasource">
      <xsd:annotation>
        <xsd:documentation>
            TODO:
        </xsd:documentation>
      </xsd:annotation>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="pool-name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- **************************************************** -->

    <xsd:complexType name="jdbc-resource-pool">
      <xsd:annotation>
        <xsd:documentation>
            TODO:
        </xsd:documentation>
      </xsd:annotation>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element type="resources:property" name="property"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- **************************************************** -->

    <xsd:complexType name="property">
      <xsd:annotation>
        <xsd:documentation>
          A name-value pair.
        </xsd:documentation>
      </xsd:annotation>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="value" type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== chyrtsik/warehouse-redo/warehouse-redo/modules/core/src/main/resources/config/resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2007-2011 Artigile.
  ~ Software art development company.
  ~ All Rights Reserved.
  ~
  ~ This software is the confidential and proprietary information of Artigile. ("Confidential Information").
  ~ You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the
  ~ license agreement you entered into with Artigile software company.
  -->

<resources xmlns="http://artigile.by/xml/ns/resources"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://artigile.by/xml/ns/resources
    http://artigile.by/xml/ns/resources/resources_1_0.xsd"
  version="1.0">
    <!-- Database server on this host -->
    <server name="localhost" datasource-name="jdbc/Warehouse-local"/>
    <datasource name="jdbc/Warehouse-local" pool-name="warehousePool-local"/>
    <jdbc-resource-pool name="warehousePool-local">
        <property name="database.url" value="jdbc:mysql://localhost:3306/warehouse?characterEncoding=utf-8"/>
        <property name="database.driver" value="org.gjt.mm.mysql.Driver"/>
        <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5InnoDBDialect"/>
    </jdbc-resource-pool>
	
	<!-- Remote database server (replace {host_name} with your server's computer name or IP) -->
  <server name="aws" datasource-name="jdbc/Warehouse-1"/>
  <datasource name="jdbc/Warehouse-1" pool-name="warehousePool-1"/>
  <jdbc-resource-pool name="warehousePool-1">
    <property name="database.url" value="jdbc:mysql://warehouse.cwbuy4k8kwpj.us-east-1.rds.amazonaws.com:3306/whclient?characterEncoding=utf-8"/>
    <property name="database.driver" value="org.gjt.mm.mysql.Driver"/>
    <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5InnoDBDialect"/>
  </jdbc-resource-pool>
	

  <!-- Remote database server (replace {host_name} with your server's computer name or IP) -->
  <server name="server01" datasource-name="jdbc/Warehouse"/>
  <datasource name="jdbc/Warehouse" pool-name="warehousePool"/>
  <jdbc-resource-pool name="warehousePool">
    <property name="database.url" value="jdbc:mysql://server01:3306/whclient?characterEncoding=utf-8"/>
    <property name="database.driver" value="org.gjt.mm.mysql.Driver"/>
    <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5InnoDBDialect"/>
  </jdbc-resource-pool>
</resources>
